### PR TITLE
You tube time lapse

### PR DESCRIPTION
**Pull request by camallen**
supersedes #94 use you tube instead of native video elements so it actually shows up as a video

### CODE REVIEW

**Comment by camallen** [comment]
deployed to https://www.penguinwatch.org/beta/#/science

**Comment by camallen** [comment]
@eatyourgreens any chance of a review on this today?

**Comment by eatyourgreens** [comment]
Looks ok to me, but we can't deploy master yet because of the new tutorial and field guide, right?

**Comment by camallen** [comment]
they've gone out already. thanks

**Pull request merged**
