### PR TITLE
reload the you tube time lapse video on translation change

### PR DESCRIPTION
**Pull request by camallen**
ensure the translated you tube content reloads properly.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks good to me. By the way, does this mean we can delete the `mp4` and `webm` files from the repo?

**Comment by eatyourgreens** [comment]
Hmmm, deployed this to https://www.penguinwatch.org/beta/#/science and the video isn't reloading when the language changes eg. from English to Spanish and back again.

**Comment by camallen** [comment]
yeah - they won't have been translated yet with the you tube code. I think zuzi was the only one that has actually translated the code.

**Comment by camallen** [comment]
and yes re those file but i left them there on purpose so we don't lose them but we can archive them elsewhere if we want.

**Comment by eatyourgreens** [comment]
I see why the video isn't showing up on the Spanish science page, but it doesn't show up when I change back to English either.

I think the problem is `window.zooniverse.LanguageManager`. I don't think that event listener will ever run, because the language manager used by the menu is a different object set here: https://github.com/zooniverse/penguinwatch/blob/master/project.coffee#L11-L24

**Comment by camallen** [comment]
right - it's working locally for me with correctly coped translation files from prod. I've added a log statement in and deployed to beta, https://www.penguinwatch.org/beta/#/science

**Comment by eatyourgreens** [comment]
Works for me in an incognito window. I must have had a cached copy of the script already.

**Comment by yshish** [comment]
Shall I edit the code translations in all other languages?

**Comment by camallen** [comment]
I did the spanish one yesterday, feel free to look at the russian one.

**Comment by eatyourgreens** [comment]
I had a look at them yesterday. I think they are all done.

**Comment by yshish** [comment]
Cool! :) Thanks

**Pull request merged**
