### PR TITLE
Update tutorial

### PR DESCRIPTION
**Pull request by mariamsaeedi**
Updated content as per Joan's request in the email:

1. Amended current final page with new image and new text.
2. Created new final page and added the other list changes to the existing classification.

Please review.

Staged at https://www.penguinwatch.org/beta/#/classify

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks good to me. The updates to the language file will have to be pushed to the translations app, so that @yshish can get them translated before this goes live.

**Comment by camallen** [comment]
remind me to update the node version this needs in engines.

**Comment by eatyourgreens** [comment]
My bad re. node version. #99 upgraded readymade to a version that doesn't work on old node versions.

**Comment by mariamsaeedi** [comment]
Updated the text on page 2 of the tutorial

**Comment by eatyourgreens** [comment]
I've published updated translations for French and Russian versions of the tutorial. I'll check with @yshish if this is ok to merge now.

**Comment by eatyourgreens** [comment]
Also, I accidentally published a couple of changes here that were meant for the live site. My bad, in a hurry to clear stuff up before going away, but that's why I've just rebased against master.

**Comment by yshish** [comment]
I think it is OK!

**Comment by eatyourgreens** [comment]
@yshish 👍

**Pull request merged**
