### PR TITLE
Field guide updates

### PR DESCRIPTION
**Pull request by camallen**
trying to get a field guide like science gossip (comes in from the left side of screen on ? button press).

@brian-c or @eatyourgreens I can't get the subject-viewer template override...thoughts?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Here you go. You have to override the templates before calling `currentProject`, which builds the page: https://github.com/zooniverse/penguinwatch/commit/b785d7cf5e08d1438338015e0b7d7f98eac198df

I'm deploying that to penguin watch.org/beta Seems to work locally.

**Comment by camallen** [comment]
cheers @eatyourgreens

**Comment by yshish** [comment]
I love the new Field Guide, just a few suggestions... 

Could you please make clearer what species belong to what image example? Currently the species name is displayed just in the middle between two images and it is not clear whether to belong to the one above or the one below once you scroll down. 

And I'm not sure whether placing the Help button above the image is to be found easily enough.. I was looking for it for a while. Moving it on the right side, near the OK button, would be probably better. What do you think?

Thanks for considering it, and many many thanks for making the changes. I'm sure the new FG would avoid many confusion we have been experiencing with new volunteers!

Cheers!

**Comment by camallen** [comment]
@yshish would flipping the label to the top work or do you have something else in mind?

@eatyourgreens any way to modify the order of the fieldguide img label in the field-guide html? I tried extracting a template for the field guide but it requires a param to be passed in and one has to override a lot of readymade.

**Comment by eatyourgreens** [comment]
@camallen override the field guides template method if you want to change the HTML c39dd0d5

By the way, the flex layout is broken in Safari. I think there's a CSS declaration missing somewhere.
pw-guide

**Comment by eatyourgreens** [comment]
ae7e6d8 should fix that layout problem

**Comment by camallen** [comment]
cheers - will get cracking on that.

**Comment by camallen** [comment]
@eatyourgreens thanks for all the help here. I think this is ready to go. @yshish can you review via, https://penguinwatch.org/beta

**Comment by yshish** [comment]
(Sorry for the delay with my reply, my laptop cracked a week ago and I've got problems getting online as often now.)

I meant to make a bigger spacing between the species names than it currently is or to divide them by a line... to make clearer on the first sight whether the sp. names belong to the image above or below it.

Then I think the current position of the Help/Field guide button is not very happily placed - I would be looking for it somewhere just next to the OK button which is used for the classification. 
When you look at other projects, it usually is close to it and so no one can miss it. The same for the Tutorial button. 
You know, until now the Field guide was open all the time visible just below the image without a need to click on anything, but you've 'hidden' it among the tiny buttons for *Hiding all marks* and *Favouriting* images which I hardly ever use at all so I don't even look at them.

If we want our volunteers to use the Field Guide(Tutorial), we should have it easily searched = visible, like when it would be just next to the buttons used for the classification. 

Or if you don't want to move the button, what about highlighting it with a colour? :)
(Hope you got my point.)

What do you think? Would it be a problem?

**Comment by camallen** [comment]
@eatyourgreens @yshish i'm not sure what the best way forward is here. 

The field guide was always below the fold on my computers and I **never** saw / used it (and i worked on this project). The idea was to move the field guide to the help button (as currently implemented) but this is inconveniently placed. I don't want to change the interface too much but could work it like science gossip, https://www.sciencegossip.org/#/classify. What do you think of that user interface @yshish ?

**Comment by yshish** [comment]
I understand you don't want to change the interface much since it always brings problems but I think it would be helpful here.

I really like the Science Gossip one, but it is placed well there - among buttons we use frequently - like zoom and BHL which are critical for the classification. 

If the changes I suggested should bring too much troubles, then make it as it is. It is not *bad*. It just could be better .)

Anyway, thanks for for the discussion.

**Comment by camallen** [comment]
@yshish moved the field guide back to bottom and removed the help text, deployed this and tutorial updates to https://penguinwatch.org/beta for final review.

**Comment by yshish** [comment]
I like it!

(Maybe you didn't have to remove the Help button but let there be both - the Field Guide at the bottom as it is now + the help button to click on, which would scroll the screen down on the FG for those with small screen who don't see it?)

**Comment by yshish** [comment]
I asked the other moderators and we agree on the current version - it is great, it is what we asked for :) :+1: Thanks a lot!

**Comment by camallen** [comment]
@yshish i've updated the tutorial steps with Tom. We've modified the text (new translations sorry) and removed some steps. Can you please review with the other mods and let us know your thoughts?

On https://penguinwatch.org/beta again.

**Comment by yshish** [comment]
I like it, I will translate it tonight.

**Comment by camallen** [comment]
It's not deployed yet so no new translations until it's done. Sounds like everyone is happy on this and the tutorial changes. @eatyourgreens fancy another review of this and #93 ?

**Comment by camallen** [comment]
@brian-c @eatyourgreens same again, can one of you review this please? We're super close to completing the latest round of data in PW and wan't to be able to re-launch new data with the UI changes.

**Comment by eatyourgreens** [comment]
Looks good to me.

**Pull request merged**
