### PR TITLE
add distant / blurred steps to tutorial

### PR DESCRIPTION
**Pull request by camallen**
Added extra steps to tutorial as requested by the PW talk moderators

### CODE REVIEW

**Comment by camallen** [comment]
I tried adding this to the field guide but it didn't work very well, screenshots of the new tutorial sections. Note: i've changed the last talks slide text ending but I'm not happy with it (and it'll require re-translation), thoughts on removing / placement?

image

image

**Comment by camallen** [comment]
@yshish thoughts?

**Comment by eatyourgreens** [comment]
Deployed to https://www.penguinwatch.org/beta along with #92 so that you can compare translations.

**Comment by camallen** [comment]
@brian-c @eatyourgreens can one of you review this please. We're super close to completing the latest round of data in PW and wan't to be able to re-launch new data with the UI changes.

**Pull request merged**
